#!/usr/bin/env bash

has_cmd() {
  for opt in "$@"; do
    if command -v "$opt" >/dev/null; then
      continue
    else
      return "$?"
    fi
  done
}

mime=$(file -bLs --mime-type "$1")
category=${mime%%/*}
kind=${mime##*/}

ext=""
if [[ "$1" == *"."* ]]; then
  ext=${1##*.}
fi

if [ "$kind" = json ]; then
  if has_cmd jupyter bat && [ "$ext" = ipynb ]; then
    jupyter nbconvert --to python --stdout "$1" | bat --color=always -plpython
  elif has_cmd jq; then
    jq -Cr . "$1"
  fi

elif [ -d "$1" ]; then
  if has_cmd eza; then
    eza --color=always --icons --tree --level=1 "$1"
  elif has_cmd exa; then
    exa --color=always --icons -hl "$1"
  fi

elif [[ "$kind" == "zip" ]]; then
  7z l "$1" | tail -n +15

elif [[ "$kind" == *"epub"* ]] || [[ "$kind" = "zip" ]]; then
  pandoc "$1"

elif [ "$kind" = pdf ]; then
  echo "$1"
  if has_cmd pdftotext sed; then
    pdftotext -q "$1" - | sed "s/\f/$(hr ─)\n/g"
  fi

elif [ "$category" = image ]; then
  echo "$1"
  kitten icat --clear --transfer-mode=stream --unicode-placeholder --align=center --stdin=no --place="${FZF_PREVIEW_COLUMNS}x$((FZF_PREVIEW_LINES - 1))@0x0" "$1"
  printf "%s" "$(hr -)"
  mediainfo "$1" | bat --color=always -plyaml
  printf "%s\n\n" "$(hr -)"
  exiftool "$1" | bat --color=always -plyaml

elif [[ "$category" = video ]] || [[ "$category" = audio ]]; then
  if has_cmd mediainfo; then
    mediainfo "$1" | bat --color=always -plyaml
  fi

elif [[ "$kind" == *"vnd.openxmlformats-officedocument.spreadsheetml.sheet" ]] ||
  [[ "$kind" == *"vnd.ms-excel" ]]; then
  in2csv "$1" | xsv table | bat -ltsv --color=always

elif [ "$kind" = x-executable ] || [ "$kind" = octet-stream ]; then
  echo "$1"
  hexyl "$1"

elif [[ "$ext" =~ md|markdown ]]; then
  paper --h-margin=3 --v-margin=1 --width=80 --tab-length=2 --syncat --hide-urls "$1" 
  # glow "$1"
  # mdless "$1"

elif [ "$category" = text ] || [[ $(file "$1") =~ "ASCII text" ]]; then
  bat --color=always --style=header "$1"

else
  if [[ -n "$1" ]]; then
    echo "Path:       $1"
    # echo "Ext:        $ext"
    echo "Mime:       $mime"
    # echo "- Category: $category"
    # echo "- Kind:     $kind"
    hr -
    file "$1"
  fi
  exit 1
fi
