[tools]
argocd = "latest"
awscli = "latest"
dagger = "latest"
dapr = "latest"
flux2 = "latest"
gitleaks = "latest"
kubectl = "latest"
nodejs = "latest"
opentofu = "latest"
packer = "latest"
pnpm = "latest"
pre-commit = "latest"
stern = "latest"
tekton-cli = "latest"
terraform = "latest"
yarn = "4"

"npm:extension" = "1.5.0"
"npm:npkill" = "latest"
"npm:pm2" = "latest"
"npm:ttab" = "latest"
"npm:yo" = "latest"

[settings]
experimental = true
