[tools]
nodejs = "latest"
pnpm = "latest"
kubectl = "latest"

tekton-cli = "latest"
dagger = "latest"
argocd = "latest"
flux2 = "latest"
stern = "latest"
"npm:extension" = "1.5.0"
dapr = "latest"
yarn = "4"
"npm:npkill" = "latest"
"npm:yo" = "latest"
gitleaks = "latest"
pre-commit = "latest"

[settings]
experimental = true
