[tools]
argocd = "latest"
awscli = "latest"
dagger = "latest"
dapr = "latest"
flux2 = "latest"
gitleaks = "latest"
kubectl = "latest"
nodejs = "latest"
opentofu = "latest"
packer = "latest"
pre-commit = "latest"
stern = "latest"
tekton-cli = "latest"
terraform = "latest"
yarn = "4"

"npm:extension" = "1.5.0"
"npm:npkill" = "latest"
"npm:pm2" = "latest"
"npm:ttab" = "latest"
"npm:yo" = "latest"
"npm:prettier" = "latest"
"npm:@vscode/vsce" = "latest"
node = "18"
"npm:markmap-cli" = "latest"
"npm:concurrently" = "latest"
pnpm = "9.10.0"

[settings]
experimental = true
