# Maximize or restore the preview pane
[[manager.prepend_keymap]]
on = [".", "s"]
run = "plugin what-size"
desc = "Calc size of selection or cwd"

[[manager.prepend_keymap]]
on = "!"
run = 'shell "$SHELL" --block --confirm'
desc = "Open shell here"

[[manager.prepend_keymap]]
on = ["c", "p"]
run = "plugin command"
desc = "Yazi command prompt"

[[manager.prepend_keymap]]
on = "E"
run = "plugin eza-preview"
desc = "Toggle tree/list dir preview"

# Show size of selection or cwd
[[manager.prepend_keymap]]
on = [".", "s"]
run = "plugin what-size"
desc = "Calc size of selection or cwd"

[[manager.prepend_keymap]]
on = "T"
run = "plugin --sync max-preview"
desc = "Maximize or restore preview"
