#!/usr/bin/env bash

#
# fzf-rg: Switch files by content using Ripgrep then filter the results with fzf
#
# - Tip: Bind to Ctrl-F

/usr/bin/rm -f /tmp/fzf-rg-{r,f}

RG_PREFIX="rg --line-number --no-heading --color=always --smart-case --colors=path:style:underline --colors=line:style:underline --colors=line:fg:white --colors=match:style:nobold --colors=match:fg:197,209,222 --colors=match:bg:45,88,156"
INITIAL_QUERY="${*:-}"

# shellcheck disable=SC2016
: | fzf --ansi --disabled --query "$INITIAL_QUERY" \
  --bind "change:reload:sleep 0.1; $RG_PREFIX {q} || true" \
  --bind 'ctrl-f:transform:[[ ! $FZF_PROMPT =~ ripgrep ]] &&
              echo "rebind(change)+change-prompt(1. 󱩾 ripgrep> )+disable-search+transform-query:echo \{q} > /tmp/fzf-rg-f; cat /tmp/fzf-rg-r" ||
              echo "unbind(change)+change-prompt(2. 󰈲 fzf> )+enable-search+transform-query:echo \{q} > /tmp/fzf-rg-r; cat /tmp/fzf-rg-f"' \
  --color "header:italic,hl:-1:underline,hl+:-1:underline:reverse" \
  --color "pointer:white" \
  --color "label:italic" \
  --border-label "╢ fzf-rg: Search files by content ╟" \
  --prompt '1. 󱩾 ripgrep> ' \
  --delimiter : \
  --layout=reverse \
  --header '<Ctrl-F> Switch to fzf/ripgrep' \
  --preview 'bat --color=always --highlight-line {2} -- {1}' \
  --preview-window 'down,50%,+{2}+3/3,~3' \
  --bind 'enter:execute(nvim {1} +{2})' \
  --bind 'alt-enter:execute(code --disable-extensions -g {1}:{2}; sleep 1)'
