#!/usr/bin/env bash

#
# fzf-man-cleanup: cleanup cache from fzf-man
#

manlist_file="/tmp/fzf-man-manlist"
cheatlist_file="/tmp/fzf-man-cheatlist"
tldrlist_file="/tmp/fzf-man-tldrlist"
export compgenlist_file="/tmp/fzf-man-compgenlist"

/usr/bin/rm $manlist_file $cheatlist_file $tldrlist_file $compgenlist_file
