#!/usr/bin/env bash

#
#  Search all files (PDF, epub...) by content
#

RG_PREFIX="rga --files-with-matches --color=always"
file="$(
  FZF_DEFAULT_COMMAND="$RG_PREFIX '$1'" \
    fzf --sort --preview="[[ ! -z {} ]] && rga --pretty --context 5 {q} {}" \
    --phony -q "$1" \
    --layout=reverse \
    --color "label:italic" \
    --border-label "╢ rga-fzf: Search all files (PDF, epub...) by content ╟" \
    --prompt '1. 󱩾 rga> ' \
    --bind "change:reload:$RG_PREFIX {q}" \
    --preview-window="right" \
    --bind='alt-z:toggle-preview-wrap' \
    --bind='ctrl-y:execute-silent(echo -n {} | xclip -selection clipboard)' \
    --bind='ctrl-s:toggle-sort'
)" &&
  echo "Opening $file" &&
  $EDITOR "$file"
