#!/usr/bin/env bash

#
# gitop: cd to top level of git repository
#

project_root="$(git rev-parse --show-toplevel)"

if [[ -n "${project_root}" ]]; then
  cd "$project_root" || return
fi

zle && zle reset-prompt
