# "$schema" = "https://mise.jdx.dev/schema/mise.json"

[tools]
# argocd = "latest"
awscli = "latest"
# dagger = "latest"
# dapr = "latest"
# flux2 = "latest"
gitleaks = "latest"
# istioctl = "latest"
kubectl = "1.33.0"
node = "latest"
opentofu = "latest"
# packer = "latest"
pnpm = "10.10.0"
# pre-commit = "latest"
# stern = "latest"
# tekton-cli = "latest"
# terraform = "latest"
yarn = "4"

"npm:@vscode/vsce" = "latest"
"npm:concurrently" = "latest"
# "npm:extension" = "1.5.0"
"npm:markmap-cli" = "latest"
"npm:npkill" = "latest"
"npm:pm2" = "latest"
"npm:ttab" = "latest"
"npm:yo" = "latest"
"npm:taze" = "latest"
"npm:wipeclean" = "latest"
"ubi:goreleaser/goreleaser" = "latest"
"ubi:Cretezy/lazyjj" = "latest"
"ubi:jesusprubio/up" = "latest"
npm = "latest"
java = "17"
aws-sam-cli = "latest"
pkl = "latest"
hk = "latest"
"npm:aws-cdk" = "latest"
"npm:defuddle-cli" = "latest"
"npm:serve" = "latest"
"npm:picgo" = "latest"
"npm:eslint_d" = "latest"
"npm:svgo" = "latest"
"npm:vercel" = "latest"
"npm:@aws/cloudfront-hosting-toolkit" = "latest"
k6 = "latest"

[settings]
experimental = true
idiomatic_version_file_enable_tools = ["node"]

[settings.node]
gpg_verify = false
